### ISSUE TITLE
IllegalStateException in OperatorWindowWithTime$ExactSubscriber.nextWindow

### ISSUE THREAD

**Issue by darkone23** [ReactiveX/RxScala#169]
I'm still trying to track the root cause of this in my code but the stacktrace is:

```
Exception in thread "RxComputationThreadPool-1" java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:148)
        at java.util.AbstractList.add(AbstractList.java:108)
        at rx.internal.operators.OperatorWindowWithTime$ExactSubscriber.nextWindow(OperatorWindowWithTime.java:294)
        at rx.internal.operators.OperatorWindowWithTime$ExactSubscriber$1.call(OperatorWindowWithTime.java:282)
        at rx.Scheduler$Worker$1.call(Scheduler.java:120)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        ... 7 more
```

Looks like the `.tumbling` operator is doing something it shouldn't be...

**Comment by darkone23** [comment]
Using `io.reactivex:rxscala_2.11:0.24.1`

**Comment by zsxwing** [comment]
Could you post your code? How do you use `tumbling`? Because if the source Observable has some concurrent issue, it may cause this exception.

**Comment by darkone23** [comment]
Here is a rough snippet:

``` scala

Observable.from(myIterable)
  .tumbling(duration, maxNum)
  .concatMap { window =>
    val out = PublishSubject[Path]()
    window.foreach(
      onNext = { msg =>
        writer.write(msg)
      },
      onError = { err =>
        out.onError(err)
      },
      onComplete = { () =>
        writer.commit(fs).foreach(out.onNext)
        out.onCompleted()
      }
    )
    out
  }

```

**Comment by darkone23** [comment]
Looking again in that stacktrace it looks like it is coming from rxjava:

```
rx.internal.operators.OperatorWindowWithTime$ExactSubscriber.nextWindow(OperatorWindowWithTime.java:294)
```

My guess is that it happens while trying to roll a window during long GC pauses - I've only ever seen it happen under load.

I wonder if it is fixed with the latest version of rxjava as I am using the older version depended on by rxscala 0.24.1.

I will do more investigation and get back,
-- Thomas

**Comment by zsxwing** [comment]
> I wonder if it is fixed with the latest version of rxjava as I am using the older version depended on by rxscala 0.24.1.

You can add RxJava to your dependencies and set the RxJava version by yourself. 

I just reviewed the `window` operator in RxJava and could not find any problem. Is there any other operator in your codes before `tumbling`? I guess one of the upstream operators sends `onNext` and `onError` at the same time. If so, it may crash the `window` operator.

**Comment by zsxwing** [comment]
@eggsby could you try 0.25.0 and see if the bug is gone?

**Comment by darkone23** [comment]
@zsxwing - Thank you for looking into this for me, I'm going to close this issue since it is doesn't appear to be a bug in rxscala and looks like it lies either in rxjava or my own code.

I'll upgrade to 0.25.0 and report back in case anyone runs into something similar.

Thanks again!
-- Thomas
