### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: rx.functions.Func1

### ISSUE THREAD

**Issue by asethia** [ReactiveX/RxScala#173]
Hi,

I am trying to run simple hello example

import rx.lang.scala._
import scala.concurrent.duration._
import scala.language.postfixOps

object HelloWorldObservable extends App{

   override def main(args: Array[String]) {
     val ticks:Observable[Long]=Observable.interval(1 seconds)
     val evens:Observable[Long]=ticks.filter(_%2==0)
     val bufs:Observable[Seq[Long]]=evens.slidingBuffer(count=2, skip=1)
     val s=bufs.subscribe(println(_))
     readLine()
     s.unsubscribe()
   }
}

I am getting following error 

Caused by: java.lang.ClassNotFoundException: rx.functions.Func1
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 2 more

It is using rxscala_2.11.

Please let me know what is missing.

Regards,
Arun

**Comment by asethia** [comment]
Scala version  2.11.5

**Comment by samuelgruetter** [comment]
What command did you use to run it? You probably miss the RxJava JAR on the classpath.

**Comment by asethia** [comment]
yes I able to fix by adding rxjava-1.0.12.jar 

thanks a lot.
