### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: io/opentracing/Tracer

### ISSUE THREAD

**Issue by kuldeepBorchate009** [ReactiveX/RxScala#240]
package com.Couchbase;

import com.couchbase.client.java.Bucket;
import com.couchbase.client.java.Cluster;
import com.couchbase.client.java.CouchbaseCluster;

public class CDBDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
	Cluster cluster=CouchbaseCluster.create("127.0.0.1");
		cluster.authenticate("", "");
		Bucket bucket=cluster.openBucket("");
	}

}
Exception in thread "main" java.lang.NoClassDefFoundError: io/opentracing/Tracer
	at com.couchbase.client.java.CouchbaseCluster.create(CouchbaseCluster.java:170)
	at com.couchbase.client.java.CouchbaseCluster.create(CouchbaseCluster.java:157)
	at com.Couchbase.CDBDemo.main(CDBDemo.java:12)
Caused by: java.lang.ClassNotFoundException: io.opentracing.Tracer
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more

Getting this error while connecting to CouchBase DB even after adding below jars

om.couchbase.client:java-client:2.6.0

com.couchbase.client:core-io:1.6.0

io.reactivex:rxjava:1.3.7

**Comment by dhoepelman** [comment]
This seems unrelated to RxScala, it does nothing with opentracing
